// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.MarineWeather
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("location")]
        public Location Location { get; set; }

        [JsonProperty("weather")]
        public Weather Weather { get; set; }
    }

    public partial class Location
    {
        [JsonProperty("lat")]
        public double Lat { get; set; }

        [JsonProperty("lon")]
        public double Lon { get; set; }
    }

    public partial class Weather
    {
        [JsonProperty("maxtempc")]
        public double Maxtempc { get; set; }

        [JsonProperty("maxtempf")]
        public long Maxtempf { get; set; }

        [JsonProperty("mintempc")]
        public double Mintempc { get; set; }

        [JsonProperty("mintempf")]
        public double Mintempf { get; set; }

        [JsonProperty("avgtempc")]
        public double Avgtempc { get; set; }

        [JsonProperty("avgtempf")]
        public double Avgtempf { get; set; }

        [JsonProperty("maxwindmph")]
        public long Maxwindmph { get; set; }

        [JsonProperty("maxwindkph")]
        public double Maxwindkph { get; set; }

        [JsonProperty("totalprecipmm")]
        public double Totalprecipmm { get; set; }

        [JsonProperty("totalprecipin")]
        public double Totalprecipin { get; set; }

        [JsonProperty("totalsnowcm")]
        public long Totalsnowcm { get; set; }

        [JsonProperty("avgviskm")]
        public double Avgviskm { get; set; }

        [JsonProperty("avgvismiles")]
        public long Avgvismiles { get; set; }

        [JsonProperty("moonphase")]
        public string Moonphase { get; set; }

        [JsonProperty("moonillumination")]
        public long Moonillumination { get; set; }
    }
}
